apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: trino-poc-cluster
  region: us-east-1
  version: "1.27"
nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20