apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-api
  labels:
    app: trino-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trino-api
  template:
    metadata:
      labels:
        app: trino-api
    spec:
      containers:
      - name: trino-api
        image: ${ECR_REGISTRY}/trino-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: TRINO_HOST
          value: "trino-coordinator"
        - name: TRINO_PORT
          value: "8080"
        - name: AWS_REGION
          value: "us-east-1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: trino-api
spec:
  selector:
    app: trino-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer 