coordinator:
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"
  config:
    query:
      max-memory: "3GB"
      max-memory-per-node: "1GB"
    memory:
      heap-headroom: "1GB"

worker:
  replicas: 2
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"
  config:
    query:
      max-memory: "3GB"
      max-memory-per-node: "1GB"
    memory:
      heap-headroom: "1GB"

catalogs:
  hive:
    properties:
      hive.s3.aws-access-key: ${AWS_ACCESS_KEY_ID}
      hive.s3.aws-secret-key: ${AWS_SECRET_ACCESS_KEY}
      hive.s3.region: us-east-1
      hive.s3.endpoint: https://s3.amazonaws.com
      hive.s3.path-style-access: "true"
      hive.s3.ssl.enabled: "true" 